# Generated by Django 2.0 on 2018-12-11 09:44

import apps.util.mixins
from decimal import Decimal
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('velocify_milestone_id', models.FloatField(blank=True, null=True)),
                ('task_dropdown', models.CharField(blank=True, choices=[('Agent Milestone Followup', 'Agent Milestone Followup'), ('Lead Follow up', 'Lead Follow up'), ('Lender Follow up', 'Lender Follow up')], max_length=64)),
                ('source_lead_id', models.CharField(blank=True, max_length=32)),
                ('send_realtor_status_email', models.BooleanField(default=None)),
                ('seller', models.BooleanField(default=None)),
                ('realtor_unresponsive', models.BooleanField(default=None)),
                ('realtor_feedback', models.TextField(blank=True)),
                ('real_estate_agent_confirmed', models.BooleanField(default=None)),
                ('real_estate_agent_assigned', models.BooleanField(default=None)),
                ('purchase_price', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12)),
                ('pre_approval_granted', models.BooleanField(default=None)),
                ('pre_approval_amount', models.FloatField(blank=True, null=True)),
                ('owner_id', models.CharField(blank=True, max_length=36)),
                ('milestones', models.CharField(blank=True, choices=[('Customer Still Searching for home', 'Customer Still Searching for home'), ('Customer Offer Submitted', 'Customer Offer Submitted'), ('Customer Ratified Contract', 'Customer Ratified Contract'), ('Customer Still Searching for home', 'Customer Still Searching for home'), ('Customer Offer Submitted', 'Customer Offer Submitted'), ('Customer Ratified Contract', 'Customer Ratified Contract'), ('Customer Closing Confirmed', 'Customer Closing Confirmed'), ('Archived', 'Archived'), ('Searching Reset', 'Searching Reset'), ('Search for Home on Hold', 'Search for Home on Hold'), ('Customer No Longer Looking', 'Customer No Longer Looking'), ('Customer No Longer Responding', 'Customer No Longer Responding'), ('Using a Different Realtor', 'Using a Different Realtor'), ('Unqualified', 'Unqualified')], max_length=128)),
                ('milestone_status_reason', models.CharField(blank=True, choices=[('Considering Another Lender', 'Considering Another Lender'), ('Considering Another Realtor', 'Considering Another Realtor'), ('Realtor Not Responding', 'Realtor Not Responding'), ('Loan Officer Not Responding', 'Loan Officer Not Responding'), ('Found Another Realtor', 'Found Another Realtor'), ('Found Another Lender', 'Found Another Lender'), ('Customer Plans Fell Through', 'Customer Plans Fell Through'), ('Customer is No Longer Interested in Buying/Selling', 'Customer is No Longer Interested in Buying/Selling'), ('Appointment Set', 'Appointment Set'), ('Viewing Homes', 'Viewing Homes')], max_length=64)),
                ('lo_has_been_briefed', models.BooleanField(default=None)),
                ('lead_status', models.CharField(blank=True, max_length=32)),
                ('lead_number', models.CharField(blank=True, max_length=36)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('last_activity_date', models.DateField(null=True)),
                ('last_activity', models.DateField(null=True)),
                ('last_action', models.CharField(blank=True, max_length=256)),
                ('hc_realtor_responsiveness', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('hc_realtor_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('hc_realtor_knowledge', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('hc_realtor_cs', models.CharField(blank=True, max_length=256)),
                ('hc_realtor_comments', models.CharField(blank=True, max_length=2048)),
                ('hc_lo_responsiveness', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('hc_lo_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('hc_lo_knowledge', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('hc_lo_cs', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('hc_lo_comments', models.CharField(blank=True, max_length=2048)),
                ('hc_general_comments', models.TextField(blank=True)),
                ('gift_card_sent_date', models.DateField(blank=True, null=True)),
                ('estimated_closing_date', models.DateField(blank=True, null=True)),
                ('do_not_sms', models.BooleanField(default=None)),
                ('date_closed', models.DateField(blank=True, null=True)),
                ('customer_still_searching', models.BooleanField(default=None)),
                ('customer_realtor_comments', models.TextField(blank=True)),
                ('customer_realtor_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('customer_rating_comments', models.CharField(blank=True, max_length=2048)),
                ('customer_nps', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12)),
                ('customer_lo_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('customer_lo_comments', models.TextField(blank=True)),
                ('customer_hc_rep_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('customer_hc_rep_comments', models.TextField(blank=True)),
                ('customer_general_comments', models.CharField(blank=True, max_length=2048)),
                ('customer_feedback', models.TextField(blank=True)),
                ('customer_closed', models.BooleanField(default=None)),
                ('current_status', models.CharField(blank=True, max_length=128)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=128)),
                ('comments_for_banks', models.TextField(blank=True)),
                ('closing_documents_received', models.BooleanField(default=None)),
                ('cash_back_amount', models.CharField(blank=True, max_length=32)),
                ('buyer_seller', models.CharField(blank=True, choices=[('Buyer', 'Buyer'), ('Seller', 'Seller'), ('Both', 'Both')], max_length=16)),
                ('buyer', models.BooleanField(default=None)),
                ('bank_name_account', models.CharField(blank=True, max_length=128)),
                ('account_type', models.CharField(blank=True, choices=[('Analyst', 'Analyst'), ('Competitor', 'Competitor'), ('Customer', 'Customer'), ('Integrator', 'Integrator'), ('Investor', 'Investor'), ('Partner', 'Partner'), ('Press', 'Press'), ('Prospect', 'Prospect'), ('Reseller', 'Reseller'), ('Other', 'Other')], max_length=16)),
                ('account_lost', models.BooleanField(default=None)),
            ],
            options={
                'abstract': False,
            },
            bases=(apps.util.mixins.UserModelLinkMixin, models.Model),
        ),
    ]
