# Generated by Django 2.0 on 2018-12-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20181222_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='hc',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
