# Generated by Django 2.1 on 2018-12-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20181223_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account_at_risk',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_lo_rating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='hc_realtor_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
