# Generated by Django 2.1 on 2019-01-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20181225_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='languages_spoken',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
