# Generated by Django 2.1 on 2019-01-10 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_auto_20190110_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prequalificationrequest',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prequalificationrequests', to='customer.Customer'),
        ),
        migrations.AlterField(
            model_name='prequalificationrequest',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='valuationrequest',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuationrequests', to='customer.Customer'),
        ),
        migrations.AlterField(
            model_name='valuationrequest',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
