# Generated by Django 2.1 on 2019-01-10 12:23

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models

def clear_languages_spoken(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Customer = apps.get_model('customer', 'Customer')
    for customer in Customer.objects.all():
        if customer.languages_spoken in (None, ''):
            customer.languages_spoken = "[]"
            customer.save()

class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_auto_20190110_0340'),
    ]

    operations = [
        migrations.RunPython(clear_languages_spoken),
        migrations.AlterField(
            model_name='customer',
            name='languages_spoken',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='milestones',
            field=models.CharField(blank=True, choices=[('Customer Offer Submitted', 'Offer Submitted'), ('Using a Different Realtor', 'Using a Different Realtor'), ('Searching Reset', 'Searching Reset'), ('Customer Ratified Contract', 'Ratified Contract'), ('Customer Closing Confirmed', 'Closing Confirmed'), ('Customer Still Searching for home', 'Still Searching for home'), ('Search for Home on Hold', 'Search on Hold'), ('Customer No Longer Looking', 'No Longer Looking'), ('Customer No Longer Responding', 'No Longer Responding'), ('Unqualified', 'Unqualified'), ('Purchase Offer Submitted', 'Purchase Offer Submitted'), ('Home Sold', 'Home Sold'), ('Archived', 'Archived'), ('Customer Home Listed', 'Home Listed')], max_length=128),
        ),
    ]
