# Generated by Django 2.1 on 2019-01-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_auto_20190110_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerstatusupdate',
            name='is_auto_created',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
