# Generated by Django 2.1 on 2019-01-11 10:39

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20190110_0251'),
        ('requirement', '0005_auto_20190103_1647'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0016_customerstatusupdate_is_auto_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('request_type', models.CharField(choices=[('Status Update', 'Status Update'), ('Pre Qualification Request', 'Pre Qualification Request'), ('Valuation Request', 'Valuation Request')], default='Status Update', max_length=64)),
                ('is_updated', models.BooleanField(default=False)),
                ('previous_milestone', models.CharField(blank=True, choices=[('Customer Still Searching for home', 'Still Searching for home'), ('Customer Offer Submitted', 'Offer Submitted'), ('Customer Ratified Contract', 'Ratified Contract'), ('Customer Closing Confirmed', 'Closing Confirmed'), ('Archived', 'Archived'), ('Searching Reset', 'Searching Reset'), ('Search for Home on Hold', 'Search on Hold'), ('Customer No Longer Looking', 'No Longer Looking'), ('Customer No Longer Responding', 'No Longer Responding'), ('Using a Different Realtor', 'Using a Different Realtor'), ('Unqualified', 'Unqualified'), ('Customer Home Listed', 'Home Listed'), ('Purchase Offer Submitted', 'Purchase Offer Submitted'), ('Home Sold', 'Home Sold')], max_length=128)),
                ('is_auto_created', models.BooleanField(default=False, null=True)),
                ('valuation', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12)),
                ('pre_qualification_amount', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12)),
                ('pre_qualification_expiry', models.DateField(null=True)),
                ('notes', models.TextField(blank=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customerstatusupdaterequests_closed', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_history', to='customer.Customer')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_history', to='property.Property')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customerstatusupdaterequests_created', to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_history', to='requirement.Requirement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='customerstatusupdate',
            name='closed_by',
        ),
        migrations.RemoveField(
            model_name='customerstatusupdate',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customerstatusupdate',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='prequalificationrequest',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='valuationrequest',
            name='customer',
        ),
        migrations.DeleteModel(
            name='CustomerStatusUpdate',
        ),
        migrations.DeleteModel(
            name='PreQualificationRequest',
        ),
        migrations.DeleteModel(
            name='ValuationRequest',
        ),
    ]
