# Generated by Django 2.1 on 2019-01-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_auto_20190111_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerupdate',
            name='pre_qualification_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
