# Generated by Django 2.1 on 2019-01-21 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_auto_20190111_0241'),
        ('customer', '0010_historicalcustomer'),
    ]

    operations = [
    ]
