# Generated by Django 2.1 on 2019-01-21 10:19

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_merge_20190121_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcustomer',
            name='languages_spoken',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='milestones',
            field=models.CharField(blank=True, choices=[('Customer Still Searching for home', 'Still Searching for home'), ('Customer Offer Submitted', 'Offer Submitted'), ('Customer Ratified Contract', 'Ratified Contract'), ('Customer Closing Confirmed', 'Closing Confirmed'), ('Archived', 'Archived'), ('Searching Reset', 'Searching Reset'), ('Search for Home on Hold', 'Search on Hold'), ('Customer No Longer Looking', 'No Longer Looking'), ('Customer No Longer Responding', 'No Longer Responding'), ('Using a Different Realtor', 'Using a Different Realtor'), ('Unqualified', 'Unqualified'), ('Customer Home Listed', 'Home Listed'), ('Purchase Offer Submitted', 'Purchase Offer Submitted'), ('Home Sold', 'Home Sold')], max_length=128),
        ),
    ]
