# Generated by Django 2.1 on 2019-02-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_auto_20190121_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerupdate',
            name='request_type',
            field=models.CharField(choices=[('Status Update', 'Status Update'), ('Pre Qualification Request', 'Pre Qualification Request'), ('Valuation Request', 'Valuation Request'), ('Realtor Requested', 'Realtor Requested')], default='Status Update', max_length=64),
        ),
    ]
