# Generated by Django 2.1 on 2019-02-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_auto_20190204_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_mls_auto_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='is_mls_auto_created',
            field=models.BooleanField(default=False),
        ),
    ]
