# Generated by Django 2.0 on 2018-12-11 09:44

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('util', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('work_history', models.IntegerField(default=0)),
                ('website_1', models.URLField(blank=True)),
                ('website_2', models.URLField(blank=True)),
                ('website_3', models.URLField(blank=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('nar_status', models.CharField(blank=True, max_length=64)),
                ('master_broker_agreement_signed', models.BooleanField(default=None)),
                ('first_name', models.CharField(blank=True, max_length=64)),
                ('last_name', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('company', models.CharField(blank=True, max_length=256)),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='util.Address')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('work_history', models.IntegerField(default=0)),
                ('velocify_milestone_id', models.FloatField(blank=True, null=True)),
                ('titlee', models.CharField(blank=True, choices=[('Loan Officer', 'Loan Officer'), ('Team Lead', 'Team Lead'), ('Sales Manager', 'Sales Manager'), ('Purchasing', 'Purchasing'), ('Velocify Administrator', 'Velocify Administrator'), ('Vice President', 'Vice President'), ('Sales Assistant', 'Sales Assistant'), ('Production Assistant', 'Production Assistant'), ('Sales Agent', 'Sales Agent'), ('Branch Manager', 'Branch Manager'), ('Director', 'Director'), ('Purchase Loan Specialist', 'Purchase Loan Specialist'), ('Assistant Sales Manager', 'Assistant Sales Manager')], max_length=128)),
                ('title', models.CharField(blank=True, max_length=128)),
                ('record_type_id', models.CharField(blank=True, max_length=36)),
                ('realtor_unresponsive_count', models.IntegerField(default=0)),
                ('realtor_score', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12)),
                ('owner_id', models.CharField(blank=True, max_length=36)),
                ('number_of_current_leads', models.IntegerField(default=0)),
                ('new_score', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12)),
                ('nar_status', models.CharField(blank=True, max_length=64)),
                ('low_realtor_rating_count_from_lo', models.IntegerField(default=0)),
                ('low_realtor_rating_count_from_customer', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('leads_sent', models.IntegerField(default=0)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('high_realtor_rating_count_from_lo', models.IntegerField(default=0)),
                ('high_realtor_rating_count_from_customer', models.IntegerField(default=0)),
                ('franchisee', models.BooleanField(default=None)),
                ('do_not_sms', models.BooleanField(default=False)),
                ('deals_sent', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('counties_served', models.TextField(blank=True)),
                ('comments_reviews', models.TextField(blank=True)),
                ('closings', models.IntegerField(default=0)),
                ('closing_percentage', models.IntegerField(blank=True, null=True)),
                ('balcklisted', models.BooleanField(default=False)),
                ('average_customer_realtor_rating', models.IntegerField(default=0)),
                ('approval_status', models.CharField(blank=True, max_length=64)),
                ('military_service', models.CharField(blank=True, max_length=128)),
                ('account_lost_count', models.IntegerField(default=0)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realtors', to='util.Address')),
                ('broker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='realtor.Broker')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='realtor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RealtorCertification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('year', models.IntegerField(choices=[(1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], default=2018)),
                ('certifying_body', models.CharField(max_length=128)),
                ('realtor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='realtor.Realtor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
