# Generated by Django 2.0 on 2018-12-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='titlee',
            field=models.CharField(blank=True, choices=[('', ''), ('Loan Officer', 'Loan Officer'), ('Team Lead', 'Team Lead'), ('Sales Manager', 'Sales Manager'), ('Purchasing', 'Purchasing'), ('Velocify Administrator', 'Velocify Administrator'), ('Vice President', 'Vice President'), ('Sales Assistant', 'Sales Assistant'), ('Production Assistant', 'Production Assistant'), ('Sales Agent', 'Sales Agent'), ('Branch Manager', 'Branch Manager'), ('Director', 'Director'), ('Purchase Loan Specialist', 'Purchase Loan Specialist'), ('Assistant Sales Manager', 'Assistant Sales Manager')], max_length=128),
        ),
    ]
