# Generated by Django 2.0 on 2018-12-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0002_auto_20181211_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='company',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
