# Generated by Django 2.0 on 2018-12-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0003_auto_20181212_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='closing_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
