# Generated by Django 2.0 on 2018-12-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0004_auto_20181212_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='nar_status',
            field=models.TextField(blank=True),
        ),
    ]
