# Generated by Django 2.0 on 2018-12-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0005_auto_20181212_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='nar_status',
            field=models.TextField(blank=True),
        ),
    ]
