# Generated by Django 2.1 on 2018-12-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0007_auto_20181212_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='master_broker_agreement_signed',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='franchisee',
            field=models.BooleanField(null=True),
        ),
    ]
