# Generated by Django 2.1 on 2019-01-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lender', '0008_loanofficer_recommended_users'),
        ('realtor', '0011_auto_20190102_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='archived_loan_officers',
            field=models.ManyToManyField(to='lender.LoanOfficer'),
        ),
    ]
