# Generated by Django 2.1 on 2019-01-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0003_concierge_name'),
        ('realtor', '0012_realtor_archived_loan_officers'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='archived_concierges',
            field=models.ManyToManyField(to='concierge.Concierge'),
        ),
    ]
