# Generated by Django 2.1 on 2019-01-14 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0013_realtor_archived_concierges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtor',
            name='archived_loan_officers',
        ),
    ]
