# Generated by Django 2.1 on 2019-01-15 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0014_remove_realtor_archived_loan_officers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtor',
            name='archived_concierges',
        ),
    ]
