# Generated by Django 2.1 on 2019-01-21 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0011_auto_20190101_0243'),
        ('realtor', '0015_remove_realtor_archived_concierges'),
    ]

    operations = [
    ]
