# Generated by Django 2.1 on 2019-01-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcauth', '0010_homecaptainuser_user_type'),
        ('realtor', '0015_remove_realtor_archived_concierges'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='recommended_users',
            field=models.ManyToManyField(blank=True, related_name='recommended_realtor', to='hcauth.HomeCaptainRecommend'),
        ),
    ]
