# Generated by Django 2.1 on 2019-01-29 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0016_realtor_recommended_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtor',
            name='recommended_users',
        ),
    ]
