# Generated by Django 2.1 on 2019-02-01 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0016_merge_20190121_0201'),
        ('realtor', '0017_remove_realtor_recommended_users'),
    ]

    operations = [
    ]
