# Generated by Django 2.1 on 2018-12-29 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0003_sms'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesforceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('message', models.CharField(blank=True, max_length=512)),
                ('code', models.CharField(blank=True, max_length=256)),
                ('status', models.CharField(blank=True, max_length=256)),
                ('url', models.CharField(blank=True, max_length=512)),
                ('resource_name', models.CharField(blank=True, max_length=512)),
                ('content', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='sms',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_smses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sms',
            name='sent_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_smses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sms',
            name='to',
            field=models.CharField(max_length=16),
        ),
    ]
