# Generated by Django 2.1 on 2019-01-07 09:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('util', '0005_discourage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('recommending_object_id', models.PositiveIntegerField()),
                ('recommended_object_id', models.PositiveIntegerField()),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('recommended_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_received', to='contenttypes.ContentType')),
                ('recommending_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_given', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
