# Generated by Django 2.1 on 2019-01-07 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('util', '0008_auto_20190107_0233'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='discourage',
            unique_together={('discouraging_content_type', 'discouraging_object_id', 'discouraged_content_type', 'discouraged_object_id')},
        ),
        migrations.AlterUniqueTogether(
            name='recommend',
            unique_together={('recommending_content_type', 'recommending_object_id', 'recommended_content_type', 'recommended_object_id')},
        ),
    ]
