# Generated by Django 2.1 on 2019-01-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0009_auto_20190107_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='discourage',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recommend',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
