# Generated by Django 2.1 on 2019-01-09 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0011_auto_20190107_0535'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='discourage',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='discourage',
            name='discouraged_content_type',
        ),
        migrations.RemoveField(
            model_name='discourage',
            name='discouraging_content_type',
        ),
        migrations.AlterUniqueTogether(
            name='recommend',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='recommend',
            name='recommended_content_type',
        ),
        migrations.RemoveField(
            model_name='recommend',
            name='recommending_content_type',
        ),
        migrations.DeleteModel(
            name='Discourage',
        ),
        migrations.DeleteModel(
            name='Recommend',
        ),
    ]
