# Generated by Django 2.1 on 2019-01-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0005_remove_concierge_specialities'),
        ('property', '0014_auto_20190129_0613'),
        ('util', '0012_auto_20190108_2032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyType',
        ),
        migrations.AddField(
            model_name='address',
            name='unit_number',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
