# Generated by Django 2.1 on 2019-02-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0016_hcoutgoingemail_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='hcoutgoingemail',
            name='anymail_message_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
