# Generated by Django 2.0 on 2018-12-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='desired_state_1',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='desired_state_2',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='desired_state_3',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
