# Generated by Django 2.1 on 2018-12-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement', '0002_auto_20181212_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='customer_general_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='customer_rating_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='lo_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='lo_general_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='lo_hc_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='lo_rating_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='lo_realtor_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='realtor_client_contact_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='realtor_general_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='realtor_hc_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='realtor_lo_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='realtor_rating_commnet',
            field=models.TextField(blank=True),
        ),
    ]
