# Generated by Django 2.1 on 2019-01-04 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requirement', '0004_auto_20181226_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='loan_officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='lender.LoanOfficer'),
        ),
    ]
