# Generated by Django 2.1 on 2019-01-21 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirement', '0005_historicalrequirement'),
        ('requirement', '0005_auto_20190103_1647'),
    ]

    operations = [
    ]
