# Generated by Django 2.1 on 2019-02-01 13:57
##DATA MIGRATION TO CREATE FOLLOWERS OF BUYERS

from django.db import migrations, connection,transaction

def create_followers(apps, schema_editor):
    """
    Can't user `follow(user, object)` because models are not loaded yet
    and the following error comes.
    ```
    django.core.exceptions.ImproperlyConfigured: The model Customer 
    is not registered. Please use actstream.registry to register it.
    ```
    So using raw queries
    """
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Requirement = apps.get_model('requirement', 'Requirement')
    Follow = apps.get_model('actstream', 'Follow')
    Customer = apps.get_model('customer', 'Customer')
    content_type_id = ContentType.objects.get_for_model(Customer).id
    cursor = connection.cursor()
    insert_statement = """
    insert into actstream_follow (user_id, content_type_id, object_id, actor_only, flag, started) values (%s, %s, %s, true, '', current_timestamp)
    """
    cursor.execute("delete from actstream_follow")
    for r in Requirement.objects.all():
        params = [(r.customer.user.id, content_type_id, r.customer.id)]
        if r.realtor:
            params.append((r.realtor.user.id, content_type_id, r.customer.id))
        if r.loan_officer:
            params.append((r.loan_officer.user.id, content_type_id, r.customer.id))
        if r.concierge:
            params.append((r.concierge.user.id, content_type_id, r.customer.id))

        cursor.executemany(insert_statement, params)

        
class Migration(migrations.Migration):

    dependencies = [
        ('requirement', '0006_merge_20190121_0201'),
    ]

    operations = [
        migrations.RunPython(create_followers),
    ]
