# Generated by Django 2.0 on 2018-12-11 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('util', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('website', models.URLField(blank=True)),
                ('salesforce_id', models.CharField(max_length=36, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='util.Address')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LenderAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sf_account_id', models.CharField(blank=True, max_length=64)),
                ('lender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lender.Lender')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lender_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LenderCertification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('year', models.IntegerField(choices=[(1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], default=2018)),
                ('certifying_body', models.CharField(max_length=128)),
                ('lender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lender.Lender')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanOfficer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('velocify_milestone_id', models.FloatField(blank=True, null=True)),
                ('titlee', models.CharField(blank=True, choices=[('Loan Officer', 'Loan Officer'), ('Team Lead', 'Team Lead'), ('Sales Manager', 'Sales Manager'), ('Purchasing', 'Purchasing'), ('Velocify Administrator', 'Velocify Administrator'), ('Vice President', 'Vice President'), ('Sales Assistant', 'Sales Assistant'), ('Production Assistant', 'Production Assistant'), ('Sales Agent', 'Sales Agent'), ('Branch Manager', 'Branch Manager'), ('Director', 'Director'), ('Purchase Loan Specialist', 'Purchase Loan Specialist'), ('Assistant Sales Manager', 'Assistant Sales Manager')], max_length=128)),
                ('title', models.CharField(blank=True, max_length=128)),
                ('record_type_id', models.CharField(blank=True, max_length=36)),
                ('owner_id', models.CharField(blank=True, max_length=36)),
                ('new_score', models.IntegerField(default=0)),
                ('lead_source', models.CharField(blank=True, choices=[('Advertisement', 'Advertisement'), ('Employee Referral', 'Employee Referral'), ('External Referral', 'External Referral'), ('Partner', 'Partner'), ('Public Relations', 'Public Relations'), ('Seminar - Partner', 'Seminar - Partner'), ('Trade Show', 'Trade Show'), ('Web', 'Web'), ('Word of mouth', 'Word of mouth'), ('Other', 'Other'), ('Great Plains', 'Great Plains'), ('NASB', 'NASB')], max_length=128)),
                ('lead_number', models.CharField(blank=True, max_length=36)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('franchisee', models.BooleanField(default=None)),
                ('do_not_sms', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('credit_lead_name', models.CharField(blank=True, max_length=128)),
                ('credit_lead_converter', models.CharField(blank=True, max_length=128)),
                ('created_date', models.DateTimeField(null=True)),
                ('comments_reviews', models.TextField(blank=True)),
                ('average_of_lo_realtor_rating', models.FloatField(default=0.0)),
                ('approval_status', models.CharField(blank=True, max_length=128)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lender.Lender')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan_officer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanOfficerCertification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('year', models.IntegerField(choices=[(1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], default=2018)),
                ('certifying_body', models.CharField(max_length=128)),
                ('loan_officer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lender.LoanOfficer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
