# Generated by Django 2.0 on 2018-12-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lender', '0002_auto_20181211_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanofficer',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
