# Generated by Django 2.0 on 2018-12-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lender', '0003_auto_20181211_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lender',
            name='phone',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
