# Generated by Django 2.1 on 2018-12-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lender', '0004_auto_20181212_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanofficer',
            name='franchisee',
            field=models.BooleanField(null=True),
        ),
    ]
