# Generated by Django 2.1 on 2018-12-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lender', '0005_auto_20181223_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanofficer',
            name='amount_paid',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='loanofficer',
            name='lo_nps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanofficer',
            name='simplesms_donotsms',
            field=models.BooleanField(default=False),
        ),
    ]
