# Generated by Django 2.1 on 2019-01-21 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lender', '0007_auto_20190101_0243'),
        ('lender', '0009_remove_loanofficer_recommended_users'),
    ]

    operations = [
    ]
