# Generated by Django 2.1 on 2018-12-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0002_concierge_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='concierge',
            name='name',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
