# Generated by Django 2.1 on 2019-01-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcauth', '0007_auto_20190103_1652'),
        ('concierge', '0003_concierge_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='concierge',
            name='recommended_users',
            field=models.ManyToManyField(blank=True, related_name='recommended_concierge', to='hcauth.HomeCaptainRecommend'),
        ),
    ]
