# Generated by Django 2.0 on 2018-12-12 12:10

import apps.hcauth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecaptainuser',
            name='salesforce_id',
            field=models.CharField(default=apps.hcauth.models.get_placeholder_salesforce_id, max_length=36, unique=True),
        ),
    ]
