# Generated by Django 2.0 on 2018-12-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcauth', '0002_auto_20181212_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecaptainuser',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='homecaptainuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='homecaptainuser',
            name='phone',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
