# Generated by Django 2.1 on 2018-12-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcauth', '0003_auto_20181212_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecaptainuser',
            name='first_name',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='homecaptainuser',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, max_length=150, verbose_name='last name'),
        ),
    ]
