# Generated by Django 2.1 on 2018-12-29 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hcauth', '0004_auto_20181225_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCaptainRecommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('recommended_author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommend_model', to=settings.AUTH_USER_MODEL)),
                ('recommended_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_model', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
