# Generated by Django 2.1 on 2019-01-04 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hcauth', '0005_homecaptainrecommend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecaptainrecommend',
            name='recommended_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommend_model', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='homecaptainrecommend',
            name='recommended_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_model', to=settings.AUTH_USER_MODEL),
        ),
    ]
