# Generated by Django 2.1 on 2019-01-04 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcauth', '0006_auto_20190103_1647'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='homecaptainrecommend',
            unique_together={('recommended_author', 'recommended_user')},
        ),
    ]
