# Generated by Django 2.1 on 2019-01-09 04:32

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('hcauth', '0007_auto_20190103_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discourage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('discouraging_object_id', models.PositiveIntegerField()),
                ('discouraged_object_id', models.PositiveIntegerField()),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('emails', django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False, null=True)),
                ('discouraged_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discourages_received', to='contenttypes.ContentType')),
                ('discouraging_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discourages_given', to='contenttypes.ContentType')),
                ('users_discouraged_to', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('recommending_object_id', models.PositiveIntegerField()),
                ('recommended_object_id', models.PositiveIntegerField()),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('emails', django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False, null=True)),
                ('recommended_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_received', to='contenttypes.ContentType')),
                ('recommending_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_given', to='contenttypes.ContentType')),
                ('users_recommended_to', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='recommend',
            unique_together={('recommending_content_type', 'recommending_object_id', 'recommended_content_type', 'recommended_object_id')},
        ),
        migrations.AlterUniqueTogether(
            name='discourage',
            unique_together={('discouraging_content_type', 'discouraging_object_id', 'discouraged_content_type', 'discouraged_object_id')},
        ),
    ]
