# Generated by Django 2.1 on 2019-01-22 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcauth', '0010_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='channel_id',
            new_name='channel',
        ),
    ]
