# Generated by Django 2.1 on 2019-01-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcauth', '0010_homecaptainuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecaptainuser',
            name='alert_for_new_messages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homecaptainuser',
            name='alert_for_new_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homecaptainuser',
            name='send_new_listings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homecaptainuser',
            name='send_newsletters',
            field=models.BooleanField(default=False),
        ),
    ]
