# Generated by Django 2.1 on 2019-01-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcauth', '0011_auto_20190122_0427'),
        ('hcauth', '0010_homecaptainuser_user_type'),
    ]

    operations = [
    ]
