# Generated by Django 2.1 on 2019-01-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcauth', '0013_hcmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hcmessage',
            name='converation_id',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
