# Generated by Django 2.1 on 2019-01-25 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcauth', '0014_hcmessage_converation_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hcmessage',
            old_name='converation_id',
            new_name='conversation_id',
        ),
    ]
