# Generated by Django 2.1 on 2019-02-01 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcauth', '0011_auto_20190130_2350'),
        ('hcauth', '0015_auto_20190125_0442'),
    ]

    operations = [
    ]
