# Generated by Django 2.1 on 2019-02-06 03:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('hcauth', '0016_merge_20190201_0251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('favoriting_object_id', models.PositiveIntegerField()),
                ('favorited_object_id', models.PositiveIntegerField()),
                ('comments', models.TextField(blank=True)),
                ('favorited_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites_received', to='contenttypes.ContentType')),
                ('favoriting_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites_done', to='contenttypes.ContentType')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('favoriting_content_type', 'favoriting_object_id', 'favorited_content_type', 'favorited_object_id')},
        ),
    ]
