# Generated by Django 2.1 on 2019-02-05 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcauth', '0017_homecaptainuser_is_mls_auto_created'),
        ('hcauth', '0017_auto_20190205_1944'),
    ]

    operations = [
    ]
