# Generated by Django 2.1 on 2019-02-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcauth', '0018_merge_20190205_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecaptainuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Buyer', 'Buyer'), ('Seller', 'Seller'), ('Both', 'Both'), ('Realtor', 'Realtor'), ('Loan Officer', 'Loan Officer')], max_length=16),
        ),
    ]
