# Generated by Django 2.1 on 2019-02-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcauth', '0020_auto_20190217_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecaptainuser',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='homecaptainuser',
            name='first_name',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='homecaptainuser',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, max_length=150, verbose_name='last name'),
        ),
    ]
