# Generated by Django 2.0 on 2018-12-11 09:44

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_customer_user'),
        ('util', '0001_initial'),
        ('realtor', '0001_initial'),
        ('lender', '0001_initial'),
        ('concierge', '0002_concierge_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreQualificationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('pre_qualification_amount', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12)),
                ('pre_qualification_expiry', models.DateField(null=True)),
                ('notes', models.TextField()),
                ('closed', models.BooleanField(default=False)),
                ('loan_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lender.LoanOfficer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('target_market', models.CharField(choices=[('target_market_1', 'Target Market 1')], max_length=64)),
                ('target_price', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12)),
                ('square_feet', models.IntegerField(default=0)),
                ('bedrooms', models.IntegerField(default=0)),
                ('bathrooms', models.IntegerField(default=0)),
                ('pre_qualification_amount', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12)),
                ('pre_qualification_expiry', models.DateField(null=True)),
                ('valuation', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12)),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='util.Address')),
                ('concierge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='concierge.Concierge')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('loan_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lender.LoanOfficer')),
                ('property_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='util.PropertyType')),
                ('realtor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='realtor.Realtor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ValuationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('valuation', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12)),
                ('notes', models.TextField()),
                ('closed', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Property')),
                ('realtor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='realtor.Realtor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='prequalificationrequest',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Property'),
        ),
        migrations.AddField(
            model_name='favoriteproperty',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Property'),
        ),
    ]
