# Generated by Django 2.1 on 2018-12-29 03:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0002_auto_20181212_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='favorite_users',
            field=models.ManyToManyField(blank=True, related_name='favorite_property', to=settings.AUTH_USER_MODEL),
        ),
    ]
