# Generated by Django 2.1 on 2018-12-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property_favorite_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='favorite_count',
            field=models.IntegerField(default=0),
        ),
    ]
