# Generated by Django 2.1 on 2018-12-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_property_recommended_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='favorite_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
