# Generated by Django 2.1 on 2018-12-30 08:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20181230_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='target_price',
            new_name='target_price_maximum',
        ),
        migrations.AddField(
            model_name='property',
            name='target_price_minimum',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12),
        ),
    ]
