# Generated by Django 2.1 on 2019-01-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_property_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
