# Generated by Django 2.1 on 2019-01-03 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_property_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='favorite_count',
        ),
    ]
