# Generated by Django 2.1 on 2019-01-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_remove_property_favorite_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='favorite_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
