# Generated by Django 2.1 on 2019-01-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20190110_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='listing_name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
