# Generated by Django 2.1 on 2019-02-01 11:22

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('realtor', '0018_merge_20190201_0251'),
        ('concierge', '0004_concierge_recommended_users'),
        ('lender', '0010_merge_20190121_0201'),
        ('customer', '0020_auto_20190121_0219'),
        ('util', '0012_auto_20190108_2032'),
        ('property', '0013_property_listing_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProperty',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False)),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('listing_name', models.CharField(blank=True, max_length=256)),
                ('target_market', models.CharField(choices=[('target_market_1', 'Target Market 1')], max_length=64)),
                ('target_price_minimum', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12)),
                ('target_price_maximum', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12)),
                ('square_feet', models.IntegerField(default=0)),
                ('bedrooms', models.IntegerField(default=0)),
                ('bathrooms', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('pre_qualification_amount', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12)),
                ('pre_qualification_expiry', models.DateField(null=True)),
                ('valuation', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12)),
                ('archived', models.BooleanField(default=False)),
                ('favorite_count', models.IntegerField(blank=True, default=0, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('address', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='util.Address')),
                ('concierge', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='concierge.Concierge')),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customer.Customer')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('loan_officer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lender.LoanOfficer')),
                #('property_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='util.PropertyType')),
                ('realtor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='realtor.Realtor')),
            ],
            options={
                'verbose_name': 'historical property',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
