# Generated by Django 2.1 on 2019-01-29 14:13

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_property_listing_name'),
    ]

    operations = [
        ##Had to manually add this step because data migrations and schema
        ##migration at the same time with default value setting
        ##was giving the following error
        
        ####django.db.utils.OperationalError:
        ####cannot ALTER TABLE "property_property" because it has pending
        ####trigger events
        
        migrations.RemoveField(
            model_name='property',
            name='property_type',
        ),
        ##
        
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, choices=[('Residential', 'Residential'), ('MultiFamily', 'MultiFamily')], default='Residential', max_length=64),
        ),
        migrations.AlterField(
            model_name='property',
            name='target_price_maximum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='target_price_minimum',
            field=models.IntegerField(default=0),
        ),
        migrations.RenameField(
            model_name='property',
            old_name='description',
            new_name='listing_description',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='listing_name',
            new_name='listing_title',
        ),
        migrations.AddField(
            model_name='property',
            name='brokerage',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='detailed_characteristics',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='disclose_address',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='expenses',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='foreclosure_status',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='property',
            name='full_bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='half_bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='lead_routing_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='property',
            name='listing_category',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='property',
            name='listing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='listing_key',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='property',
            name='listing_participants',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='listing_url',
            field=models.URLField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='property',
            name='location',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='lot_size',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='property',
            name='mls_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='modification_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='one_quarter_bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='open_houses',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='photos',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_sub_type',
            field=models.CharField(blank=True, choices=[('Cabin', 'Cabin'), ('Condominium', 'Condominium'), ('Duplex', 'Duplex'), ('Farm', 'Farm'), ('Manufactured Home', 'Manufactured Home'), ('Mobile Home', 'Mobile Home'), ('Quadruplex', 'Quadruplex'), ('Single Family Attached', 'Single Family Attached'), ('Single Family Detached', 'Single Family Detached'), ('Townhouse', 'Townhouse'), ('Triplex', 'Triplex')], default='', max_length=64),
        ),
        migrations.AddField(
            model_name='property',
            name='taxes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='three_quarter_bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='year_built',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
