# Generated by Django 2.1 on 2019-02-01 13:57
##DATA MIGRATION TO CREATE FOLLOWERS OF SELLERS

from django.db import migrations, connection,transaction

def create_followers(apps, schema_editor):
    """
    Can't user `follow(user, object)` because models are not loaded yet
    and the following error comes.
    ```
    django.core.exceptions.ImproperlyConfigured: The model Customer 
    is not registered. Please use actstream.registry to register it.
    ```
    So using raw queries
    """
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Property = apps.get_model('property', 'Property')
    Follow = apps.get_model('actstream', 'Follow')
    Customer = apps.get_model('customer', 'Customer')
    content_type_id = ContentType.objects.get_for_model(Customer).id
    cursor = connection.cursor()
    insert_statement = """
    insert into actstream_follow (user_id, content_type_id, object_id, actor_only, flag, started) values (%s, %s, %s, true, '', current_timestamp)
    """
    for p in Property.objects.all():
        params = [(p.customer.user.id, content_type_id, p.customer.id)]
        if p.realtor:
            params.append((p.realtor.user.id, content_type_id, p.customer.id))
        if p.loan_officer:
            params.append((p.loan_officer.user.id, content_type_id, p.customer.id))
        if p.concierge:
            params.append((p.concierge.user.id, content_type_id, p.customer.id))

        cursor.executemany(insert_statement, params)
        
class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_historicalproperty'),
        ('requirement', '0007_auto_20190201_0557'),
    ]

    operations = [
        migrations.RunPython(create_followers),
    ]
