# Generated by Django 2.1 on 2019-01-29 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20190129_0613'),
    ]

    operations = [
        ##cancelled by migrations 0021_property_loan_officer.py
        #migrations.RemoveField(
        #    model_name='property',
        #    name='loan_officer',
        #),
    ]
