# Generated by Django 2.1 on 2019-01-31 08:24

import apps.property.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_remove_property_loan_officer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='listing_key',
            field=models.CharField(default=apps.property.models.get_placeholder_uuid, max_length=36),
        ),
        migrations.RemoveField(
            model_name='property',
            name='mls_number',
        ),
        migrations.AddField(
            model_name='property',
            name='mls_number',
            field=models.CharField(default=apps.property.models.get_placeholder_uuid, max_length=36),
        ),
    ]
