# Generated by Django 2.1 on 2019-01-31 11:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_auto_20190131_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('media_modification_timestamp', models.DateTimeField()),
                ('media_url', models.URLField(max_length=256)),
                ('media_caption', models.CharField(blank=True, max_length=256)),
                ('media_description', models.TextField(blank=True)),
                ('s3_url', models.URLField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='property',
            name='photos',
        ),
        migrations.AddField(
            model_name='propertyphoto',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='property.Property'),
        ),
    ]
