# Generated by Django 2.1 on 2019-01-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_auto_20190131_0333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyphoto',
            name='s3_url',
        ),
        migrations.AddField(
            model_name='propertyphoto',
            name='is_in_s3',
            field=models.BooleanField(default=False),
        ),
    ]
