# Generated by Django 2.1 on 2019-01-31 13:19

from django.db import migrations, models
import django.db.models.deletion

def delete_existing_properties(apps, schema_editor):
    Property = apps.get_model('property', 'Property')
    Property.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_auto_20190131_0341'),
    ]

    operations = [
        migrations.RunPython(delete_existing_properties),
    ]
