# Generated by Django 2.1 on 2019-02-01 09:59

import apps.property.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_auto_20190131_0519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='property',
            name='pre_qualification_amount',
        ),
        migrations.RemoveField(
            model_name='property',
            name='pre_qualification_expiry',
        ),
        migrations.RemoveField(
            model_name='property',
            name='target_market',
        ),
        migrations.AlterField(
            model_name='property',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='customer.Customer'),
        ),
        migrations.AlterField(
            model_name='property',
            name='listing_key',
            field=models.CharField(default=apps.property.models.get_placeholder_uuid, max_length=36, unique=True),
        ),
        migrations.AddField(
            model_name='propertyphoto',
            name='key',
            field=models.CharField(blank=True, max_length=48),
        ),
    ]
