# Generated by Django 2.1 on 2019-02-01 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lender', '0009_remove_loanofficer_recommended_users'),
        ('property', '0020_propertyphoto_key'),
    ]

    operations = [
        ##cancelled out for migration 0015_remove_property_loan_officer.py
        #migrations.AddField(
        #    model_name='property',
        #    name='loan_officer',
        #    field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lender.LoanOfficer'),
        #),
    ]
