# Generated by Django 2.1 on 2019-02-04 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0022_property_strike'),
        ('property', '0015_auto_20190201_0557'),
    ]

    operations = [
    ]
