# Generated by Django 2.1 on 2019-02-04 10:18

import apps.property.models
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0023_merge_20190204_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproperty',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='historicalproperty',
            name='description',
        ),
        migrations.RemoveField(
            model_name='historicalproperty',
            name='listing_name',
        ),
        migrations.RemoveField(
            model_name='historicalproperty',
            name='pre_qualification_amount',
        ),
        migrations.RemoveField(
            model_name='historicalproperty',
            name='pre_qualification_expiry',
        ),
        migrations.RemoveField(
            model_name='historicalproperty',
            name='target_market',
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='brokerage',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='detailed_characteristics',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='disclose_address',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='expenses',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='foreclosure_status',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='full_bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='half_bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='lead_routing_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='listing_category',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='listing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='listing_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='listing_key',
            field=models.CharField(db_index=True, default=apps.property.models.get_placeholder_uuid, max_length=36),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='listing_participants',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='listing_title',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='listing_url',
            field=models.URLField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='location',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='lot_size',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='mls_number',
            field=models.CharField(default=apps.property.models.get_placeholder_uuid, max_length=36),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='modification_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='one_quarter_bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='open_houses',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='property_sub_type',
            field=models.CharField(blank=True, choices=[('Cabin', 'Cabin'), ('Condominium', 'Condominium'), ('Duplex', 'Duplex'), ('Farm', 'Farm'), ('Manufactured Home', 'Manufactured Home'), ('Mobile Home', 'Mobile Home'), ('Quadruplex', 'Quadruplex'), ('Single Family Attached', 'Single Family Attached'), ('Single Family Detached', 'Single Family Detached'), ('Townhouse', 'Townhouse'), ('Triplex', 'Triplex')], default='', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='property_type',
            field=models.CharField(blank=True, choices=[('Residential', 'Residential'), ('MultiFamily', 'MultiFamily')], default='Residential', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='strike',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=0),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='taxes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='three_quarter_bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='year_built',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproperty',
            name='target_price_maximum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalproperty',
            name='target_price_minimum',
            field=models.IntegerField(default=0),
        ),
    ]
