# Generated by Django 2.1 on 2019-02-04 14:43

from django.conf import settings
from django.db import migrations

def create_system_user(apps, schema_editor):
    User = apps.get_model('hcauth', 'HomeCaptainUser')
    User.objects.get_or_create(username=settings.SYSTEM_USERNAME, is_staff=True)
    Property = apps.get_model('property', 'Property')
    Property.objects.all().delete()
    
class Migration(migrations.Migration):

    dependencies = [
        ('property', '0024_auto_20190204_0218'),
    ]

    operations = [
        migrations.RunPython(create_system_user),
    ]
