# Generated by Django 2.1 on 2019-02-04 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0025_auto_20190204_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='customer.Customer'),
        ),
    ]
