# Generated by Django 2.1 on 2019-02-04 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_auto_20190204_0150'),
        ('property', '0026_auto_20190204_0649'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoriteproperty',
            unique_together={('property', 'customer')},
        ),
    ]
