# Generated by Django 2.1 on 2019-02-04 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0027_auto_20190204_1103'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoriteproperty',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='favoriteproperty',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='favoriteproperty',
            name='property',
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='lng',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='property',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='property',
            name='lng',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='FavoriteProperty',
        ),
    ]
