"""
Django settings for homecaptain project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
from celery.schedules import crontab

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'hvp*6!(er2d&16xy+7eoj4fv7pomj8s(vsd^yqdbbf-+r^9$8c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Application definition

INSTALLED_APPS = [
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.postgres',
    'django.contrib.staticfiles',

    'django_filters',
    'django_extensions',    
    'django_nose',
    'phonenumber_field',
    'corsheaders',
    'anymail',
    
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_swagger',
    'rest_auth',

    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'rest_auth.registration',
    'localflavor',
    'django_celery_results',
    
    #adding the following two because their adbsence creates errors, we don't use them as such in our code
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    'simple_history',

    'apps.util',
    'apps.hcauth', 
    'apps.customer',
    'apps.lender',
    'apps.realtor',
    'apps.concierge', 
    'apps.property',
    'apps.event',
    'apps.service_provider',
    'apps.requirement',
    #'apps.rating',

    #keep this at the last
    'actstream',
]

TEST_RUNNER = 'django_nose.NoseTestSuiteRunner'

SITE_ID = 1


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]

ROOT_URLCONF = 'homecaptain.urls'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/
STATIC_URL = '/static/'
#DIST_DIR = os.path.join(BASE_DIR, '../frontend/dist/')
DIST_DIR = os.path.join(BASE_DIR, '../portal/dist/')
REALTOR_DIST_DIR = os.path.join(BASE_DIR, '../frontend/dist/')
STATIC_DIR = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = (
    DIST_DIR,
    REALTOR_DIST_DIR,
    STATIC_DIR,
)

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            DIST_DIR, 
            REALTOR_DIST_DIR,
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'homecaptain.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases
# to be specified in local_settings

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_USER_MODEL = 'hcauth.HomeCaptainUser'
ACCOUNT_USER_MODEL_USERNAME_FIELD = 'username'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'username'
AUTHENTICATION_METHOD = ACCOUNT_AUTHENTICATION_METHOD #fix for rest_auth
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True

# LOGIN_URL = "/#/login"
# LOGIN_REDIRECT_URL = "/"

LOGIN_URL = "/api/auth/swaggerlogin/"
LOGOUT_URL = "/logout/"
LOGIN_REDIRECT_URL = "/api/docs/"

AUTHENTICATION_BACKENDS = ['apps.hcauth.hauthbackend.SwaggerBackend']

Auth_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'US/Pacific'

USE_I18N = True

USE_L10N = True

USE_TZ = True



PHONENUMBER_DEFAULT_REGION = 'US'

#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_BACKEND = "apps.util.sendgrid.HCSendgridEmailBackend"
#"anymail.backends.sendgrid.EmailBackend"

#include the file path in local_settings
SAMPLE_MLS_DATA_FILE = ''

CELERY_RESULT_BACKEND = 'django-db'
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_BEAT_SCHEDULE = {}
PORT = ""
SCHEME = "https"
OTHER_ALLOWED_HOSTS = []
try:
    from .local_settings import *
except:
    pass
CELERY_BEAT_SCHEDULE.update({
    'send-smses-every-three-minutes': {
        'task': 'send-batch-sms',
        'schedule': crontab(minute='*/3'),
    },
})

ALLOWED_HOSTS = [
     DOMAIN,
]
ALLOWED_HOSTS = ALLOWED_HOSTS + OTHER_ALLOWED_HOSTS
DOMAIN_URL = "%s://%s%s" % (SCHEME, DOMAIN, ':%s' % PORT if PORT else '')
GOOGLE_OAUTH2_CALLBACK_URL = DOMAIN_URL + '/'
GOOGLE_CODE_TO_ACCESS_TOKEN_URL = DOMAIN_URL + '/api/auth/google/'
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_ADAPTER = "apps.hcauth.adapter.HCAccountAdapter"
if DEBUG:
    CORS_ORIGIN_WHITELIST = (
        'local.homecaptain.com',
        'local.homecaptain.com:8000',
        '127.0.0.1:8000',
        'localhost:8000',
    )

DEFAULT_FROM_EMAIL = "appnotifications@homecaptain.com"
ANYMAIL = {
    'WEBHOOK_SECRET': 'RVE6qbKqC9FYiB3M:0OWPLGUoemQzlaWu',
    "SENDGRID_API_KEY": SENDGRID_API_KEY, #defined in local_settings.py.template
}


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication'
    ),
    # 'DEFAULT_PERMISSION_CLASSES': (
    #    'rest_framework.permissions.IsAdminUser',
    # ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend',)
}

##https://django-activity-stream.readthedocs.io/en/latest/data.html#custom-data
##https://github.com/justquick/django-activity-stream/pull/294
##https://github.com/kbussell/django-jsonfield-compat/issues/3
##https://github.com/justquick/django-activity-stream/blob/master/actstream/jsonfield.py
ACTSTREAM_SETTINGS = {
    'USE_JSONFIELD': True,
}
USE_NATIVE_JSONFIELD = True

##Removed session auth from API based views
##https://security.stackexchange.com/questions/166724/should-i-use-csrf-protection-on-rest-api-endpoints
##http://kylebebak.github.io/post/django-rest-framework-auth-csrf
#'rest_framework.authentication.SessionAuthentication',

DEV_EMAILS = [
    "brenton@djangoforce.com",
    "jai@djangoforce.com",
    "ani@brainfors.com",
    "johnkan@djangogorce.com",
    "brander.dev@gmail.com",
    "olegbilous32@gmail.com",
    "brian@djangoforce.com",
]

if DEBUG:
    SALESFORCE_USERNAME = 'nazir.tyrewala@homecaptain.com.sandbox42'
    SALESFORCE_PASSWORD = 'Connor#1'
    SALESFORCE_SECURITY_TOKEN = "E54iHcjpaaQd5Zs5Ea6aqWgB7"
    SALESFORCE_DOMAIN = "test"
else:
    pass
    #SALESFORCE_USERNAME = ''
    #SALESFORCE_PASSWORD = ''
    #SALESFORCE_SECURITY_TOKEN = ""
    #SALESFORCE_DOMAIN = "test"

if DEBUG:
    SEND_SMS = False
else:
    SEND_SMS = True

SWAGGER_SETTINGS = {
    'USE_SESSION_AUTH': True,
    'SECURITY_DEFINITIONS': {
        'api_Key': {
            'type': 'apiKey',
            'in': 'header',
            'name': 'Token Authorization'
        }
    }
}

ASGI_APPLICATION = "homecaptain.routing.application"
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('localhost', 6379)],
        },
    },
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {pathname} {module} {funcName} {lineno} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR + '/debug.log',
            'formatter': 'verbose'
        },
        'mail_admins': {
            'level': 'CRITICAL',
            'class': 'django.utils.log.AdminEmailHandler',
            'formatter': 'verbose'
        }
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file', 'mail_admins'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['console', 'file', 'mail_admins'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'django.server  ': {
            'handlers': ['console', 'file',  'mail_admins'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'apps': {
            'handlers': ['console', 'file', 'mail_admins'],
            'level': 'DEBUG',
            'propagate': True,
        }
    }
}

SYSTEM_USERNAME = 'hc-system'
GOOGLE_GEOCODING_API_KEY = "AIzaSyCnWtPahCKAvjgc8VhFf0bKcIV_e9A3xiM"
COUNT_OF_MLS_PROPERTIES_TO_PARSE = None


SIMILAR_PROPERTY_SEARCH_SQUARE_FEET_ALLOWANCE=0.25
