# Generated by Django 2.1 on 2019-01-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventslot',
            name='event',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_config',
        ),
        migrations.AddField(
            model_name='event',
            name='is_concierge_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_concierge_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_loan_officer_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_loan_officer_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_owner_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_owner_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_realtor_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_realtor_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_service_provider_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_service_provider_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, choices=[('', ''), ('Property Showing', 'Property Showing'), ('Sign the Agent Document', 'Sign the Agent Document')], max_length=64),
        ),
        migrations.AddField(
            model_name='event',
            name='proposed_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='proposed_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='EventConfig',
        ),
        migrations.DeleteModel(
            name='EventSlot',
        ),
    ]
