# Generated by Django 2.1 on 2019-01-04 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20190104_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.Property'),
        ),
    ]
