# Generated by Django 2.1 on 2019-01-09 04:58

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20190108_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='emails',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
