# Generated by Django 2.1 on 2019-01-09 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20190108_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_buyer_concierge_confirmed',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_buyer_confirmed',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_buyer_loan_officer_confirmed',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_buyer_realtor_confirmed',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_seller_confirmed',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_seller_realtor_confirmed',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_service_provider_confirmed',
        ),
    ]
