# Generated by Django 2.1 on 2019-01-12 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20190108_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='property.Property'),
        ),
    ]
